[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer-runs = 200
via-ir = true

remappings = [
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
fs_permissions = [{ access = "read-write", path = "../deployments" }]


# Testing
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 100 }

[lint]
exclude_lints = ["screaming-snake-case-immutable"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
